jeremyevans/rodauth

doc/jwt.rdoc, lib/rodauth/features/jwt.rb, spec/jwt_spec.rb
* Add jwt_claims and jwt_verifiers auth value methods to jwt feature and pass these along to ruby-jwt on encode/decode.
* Add jwt_nest_session? auth value method to optionally nest the session hash in the JWT payload under the 'data' key.
* Add jwt_symbolize_deeply? auth value method to optionally symbolize subhash keys when decoding the JWT payload.
Follow-up to #8!
=> Add basic support for JWT claims and verifiers

lib/rodauth/features/jwt.rb
File under "shooting myself in the foot": now that the session data is nested, in order to retrieve reserved claims from the JWT you need to write e.g. `jwt_payload['jti']`. This of course incurs an expensive call to JWT.decode each time. Here's a quick and dirty fix.
=> Memoize jwt_payload method

README.rdoc
There was a misspelling in 'Load extensions' section.
=> Update README.rdoc to fix a misspelling

lib/rodauth/features/reset_password.rb, spec/reset_password_spec.rb
I noticed that the password reset flow wasn't actually respecting the deadline column. I didn't want to break any internal APIs that someone else might be relying on, so I made the simplest change I could think of, but of course feel free to tweak this however you like. Also I opted for the path of least transparency (making the output from a missing key identical to that of an expired key), but it might be preferable for this case to trigger a "that link has expired" message.
I also ran into a second issue with password reset, for which the fix is less clear to me: if the accounts primary key is when using an integer primary key and someone visits a password reset link like `/reset-password?key=blah_blah`, Rodauth doesn't recognize that the user id isn't valid and you get a …
=> Have password reset flow respect deadlines.

doc/base.rdoc, lib/rodauth/features/base.rb
Add's a `cache_templates` method to base, with a default value of true, allowing the caching of templates to be configurable.
Stops the clobbering of the `cache` value if provided via `template_opts`.
Uses `template_opts` as the base for `button_opts`.
=> Allow cache setting to be overridden

README.rdoc, doc/base.rdoc, doc/create_account.rdoc
Rodauth doesn't use model instances anymore, it uses plain hashes instead. So, we update some leftover references of "model instances".
Closes #48
=> Update "model instance" references

README.rdoc, doc/base.rdoc
Since the second part of the sentence says that both factors have to been authenticated, I think the first part meant to say "If 2 factor authentication *has* been enabled..."
=> Fix typo in #authenticated? docs

lib/rodauth/features/disallow_common_passwords.rb
I noticed that expanding the default path for the top common passwords could be written in a shorter way.
=> Simplify expanding path

doc/login_password_requirements_base.rdoc, lib/rodauth/features/change_login.rb, lib/rodauth/features/create_account.rb, lib/rodauth/features/login_password_requirements_base.rb, lib/rodauth/features/verify_login_change.rb
Replaced hard-coded string 'already an account with this login' in several features with a single configurable `auth_value_method` in 'base' feature.
Some end-of-line spaces were automatically removed by emacs.
Added rules  to `.gitignore` to ignore files often created by a development environment.
=> replaced hard-coded string 'already an account with this login' 

lib/rodauth/features/base.rb, spec/two_factor_spec.rb, templates/otp-auth-code-field.str
This code is likely input from a separate device and any previous values are unnecessary noise. 
Adds an `attr` option to the `opts` hash passed to `input_field_string`, allowing us to pass arbitrary attributes.
=> Disable autocomplete on OTP Auth Code input

lib/rodauth/features/disallow_password_reuse.rb
When account_password_hash_column is unset and the verify account feature is not loaded, verify_account_set_password? is called raising a NoMethodError.
=> Fix disallow password reuse feature when not using verify_account

lib/rodauth/features/jwt_refresh.rb, spec/jwt_refresh_spec.rb
=> Omit jwt access_token from response on error

doc/change_login.rdoc, doc/change_password.rdoc, doc/close_account.rdoc, doc/confirm_password.rdoc, doc/create_account.rdoc, doc/email_auth.rdoc, doc/lockout.rdoc, doc/login.rdoc, doc/logout.rdoc, doc/otp.rdoc, doc/recovery_codes.rdoc, doc/remember.rdoc, doc/reset_password.rdoc, doc/sms_codes.rdoc, doc/verify_account.rdoc, doc/verify_login_change.rdoc, lib/rodauth.rb, lib/rodauth/features/base.rb, lib/rodauth/features/create_account.rb, lib/rodauth/features/email_base.rb, lib/rodauth/features/otp.rb, lib/rodauth/features/password_expiration.rb, lib/rodauth/features/recovery_codes.rb, lib/rodauth/features/reset_password.rb, lib/rodauth/features/sms_codes.rb, lib/rodauth/features/verify_account.rb
Having a relative or absolute URL to the action is useful when redirecting or displaying links. They are also used in a few places inside the Rodauth codebase, which would be useful to DRY up.
So we add `*_path` and `*_url` counterparts to each `*_route` method, which return relative and absolute URL to the route respectively.
```rb
login_route #=> "login"
login_path  #=> "<prefix>/login"
login_url   #=> "https://example.com<prefix>/login"
```
=> Add *_path and *_url counterparts to *_route methods

lib/rodauth/features/email_auth.rb, lib/rodauth/features/login.rb, spec/email_auth_spec.rb
When using the email_auth feature, we want to display the option to authentication via email when the user has entered a valid login during multi phase login.
By default, the email_auth feature overrides `#login_form_footer` to add the form for requesting email authentication. However, in my case I'm rewriting Rodauth views in Rails, and don't want to use Rodauth's view helpers such as `#login_form_footer` (I want all HTML to be contained in views).
So, I added the `#valid_login_entered?` method that reads the instance variable, which can then be called in views like this to display the email auth request form on the login page:
```rb
if rodauth.valid_login_entered?
rodauth.email_auth_request_form
end
```
We also get rid of the `@email_auth_request_form` variable, which doesn't seem to be …
=> Add #valid_login_entered? method for multi phase login

templates/email-auth-request-form.str, templates/reset-password-request.str, templates/unlock-account-request.str, templates/verify-account-resend.str
In #64 we've added `*_path` counterparts to `*_route` methods, and switched most of Rodauth to use them instead of the `*_route` methods. However, we left out templates, so this PR addresses that.
=> Use *_path methods in templates

lib/rodauth/features/login.rb
It noticed a view render that doesn't seem to be used anywhere, so I thought it's probably a leftover from a previous refactor.
=> Remove unused view render in login feature

lib/rodauth/features/create_account.rb
This puts `create_account` feature dependencies into the same `depends` call.
=> Inline create_account dependencies

lib/rodauth/features/jwt_refresh.rb
This makes jwt_refresh feature definition consistent with all other features.
=> Specify the JwtRefresh constant in the Feature.define call

lib/rodauth/features/webauthn_login.rb
This was most likely just not updated after introducing the redirect option.
=> Use webauth_login_failure_redirect on webauthn login failure

spec/two_factor_spec.rb
I noticed this spec name is the same as the first spec in this file, so I updated the description.
=> Fix duplicate spec name

lib/rodauth/features/remember.rb
This shortens a bit converting the remember key by using the `#convert_token_key` method.
=> Use #convert_token_key method for converting remember token key

templates/login-confirm-field.str, templates/login-field.str
Fixes the condition for the login autocomplete value to call the `#login_uses_email?` method.
=> Fix checking #login_uses_email? for autocomplete

README.rdoc, lib/rodauth.rb, lib/rodauth/features/base.rb, lib/rodauth/features/email_base.rb, spec/rodauth_spec.rb
As discussed on the google group, this PR adds the ability for `*_path` and `*_url` methods to accept query parameters. This allows one to replace:
```rb
"#{rodauth.create_account_path}?#{Rack::Utils.build_nested_query(foo: "bar")}"
#=> "/create-account?foo=bar"
```
with
```rb
rodauth.create_account_path(foo: "bar")
#=> "/create-account?foo=bar"
```
I needed this in my application where I wanted to customize the registration form depending on the context, which I'm passing as query parameters. And Rails didn't have any helper methods for adding query parameters to a path, so I thought it would be useful to Rodauth to have that built in.
=> Allow passing query parameters to *_path and *_url methods

lib/rodauth/features/base.rb, templates/webauthn-remove.str
As described [here](https://groups.google.com/d/msg/rodauth/j3Qc2N1R1MU/xikp41F8AQAJ), the Bootstrap 4 change introduced a regression regarding displaying the validation error message.
Bootstrap 4 requires the input field to have class `is-invalid` and to be a sibling to the `invalid-feedback` element, otherwise the `invalid-feedback` element won't be displayed.
Since the webauthn remove field error will only be displayed if no options were selected, we display the error message after the last radio button. We also use the `#input_field_string` method to get the `is-invalid` class back, but modify it to allow for checkboxes as well.
The tests are failing with this change, it seems the radio buttons are not being displayed anymore on the validation error.
=> Ensure webauthn-remove error message is displayed on Bootstrap 4

lib/rodauth/features/verify_login_change.rb
When verifying login change, the user is expected to be logged in, because prior to that they've changed their login, which required them to be logged in. This action also does generally make sense when the user is logged in.
In my case, this allows me to configure
```rb
already_logged_in { redirect login_redirect }
```
and have that be called for login, create_account and reset_password, but still allow access to the verify_login_change page.
=> Don't call #check_already_logged_in in verify_login_change

lib/rodauth/features/lockout.rb
This makes it easier to override `#send_unlock_account_email` with custom email sending, as it means that calling `#unlock_account_email_link` will just work, just like with other `#send_*_email` methods (see [rodauth-rails recommendation](https://github.com/janko/rodauth-rails/blob/7562530ea78cbf7a8bbffa8208915a0623473c1a/lib/generators/rodauth/templates/lib/rodauth_app.rb#L44-L61)).
Previously trying to call `#unlock_account_email_link` inside overridden `#send_unlock_account_email` would return an email link with empty token value, because the `@unlock_account_key_value` variable wasn't being set.
=> Generate unlock account key outside of #send_unlock_account_email

README.rdoc, www/pages/documentation.erb
This adds a section about the [rodauth-rails](https://github.com/janko/rodauth-rails) gem to the README and to the external features section.
=> Add section about rodauth-rails to the README

lib/rodauth/features/verify_account_grace_period.rb, spec/verify_account_grace_period_spec.rb
I found another angle for https://github.com/jeremyevans/rodauth/pull/91 where this change is useful, so I would like to propose this change again (I would re-open that PR but I had deleted that branch, so GitHub didn't allow it).
In https://github.com/jeremyevans/rodauth/pull/91 we discussed that, in case a user is in an unverified grace period and doesn't have a password (i.e. `verify_account_set_password?` was intentionally set to `true`), attempting to login to that account will return an error message that the password was invalid. I had agreed this behaviour seemed good enough, because I thought the only important thing is to prevent the login.
However, I realized that based on this error message the user might not realize they need to verify their account, because nothing in that …
=> Don't consider account open if in unverified grace period without password

doc/base.rdoc, lib/rodauth.rb, lib/rodauth/features/base.rb
This allows the CSRF checking logic to be overridden. For example, rodauth-rails gem can now override this method to use Action Controller for checking CSRF tokens. This means when the user or a 3rd-party gem wants to disable CSRF protection for certain routes, they can have `#check_csrf?` return false for those routes, and that would work with rodauth-rails as well (currently rodauth-rails overrides `#before_rodauth` to do its CSRF protection).
cc @HoneyryderChuck
=> Move checking CSRF token into #check_csrf method

lib/rodauth/features/jwt.rb, spec/jwt_spec.rb
JSON requests should probably not be expected to provide a CSRF token, because CSRF protection is normally not part of a JSON API. This makes JSON requests in Rodauth with both HTML and JWT route versions enabled (i.e. with `json: true`) work automatically, the user doesn't need to disable CSRF protection for JSON routes.
/cc @nicolas-besnard
=> Don't check CSRF token on JSON requests

lib/rodauth/features/two_factor_base.rb
Both of these methods call `#two_factor_authentication_setup?`, which calls `#possible_authentication_methods`, which makes additional queries. These queries are cached during a single request, but are run on every new request. It will run 1 query to load the password, and 1 query for each loaded MFA feature (OTP, SMS codes, Recovery codes etc), which puts some load on the database.
So, I thought we could changes these methods to call `#uses_two_factor_authentication?` instead, which caches the result of `#two_factor_authentication_setup?` in a session key, which persists between requests. This means `#authenticated?` and `#require_authentication` won't run any queries once the result is cached.
=> Reduce queries in #authenticated? and #require_authentication

www/pages/documentation.erb
The original heading text was "How-To", which was then changed to "Guides". This updates the anchor identifier accordingly as well.
=> Update anchor link for "Guides" heading

lib/rodauth/features/jwt_refresh.rb
I noticed that the documentation describes the hook http://rodauth.jeremyevans.net/rdoc/files/doc/jwt_refresh_rdoc.html but it doesn't work and it looks like it's not written in the code
=> Add route before hook for jwt-refresh

lib/rodauth/features/jwt_refresh.rb
This isn't needed anymore after https://github.com/jeremyevans/rodauth/commit/4c52564817bea2a982aa8fb7276925a9d345d66f.
=> Remove unnecessary variable assignment in jwt_refresh

README.rdoc, doc/password_pepper.rdoc, lib/rodauth/features/base.rb, lib/rodauth/features/disallow_password_reuse.rb, lib/rodauth/features/password_pepper.rb, spec/password_pepper_spec.rb, www/pages/documentation.erb
A password [pepper] is a secret key that's appended to the password before it's hashed. This means that, in case an attacker was able to obtain password hashes from the database, they're not able to use them to crack the passwords without also knowing the password pepper.
Password peppering is supported by Devise and Sorcery, so I thought it would be nice for Rodauth to support it too. When using Rodauth's database functions, it's already difficult for an attacker to obtain password hashes, so password peppering is mostly intended for developers that have opted out of that, but it works with database functions as well.
```rb
enable :password_pepper
password_pepper "<long secret key>"
```
Pepper rotation is considered one of the difficulties when using peppers (neither Devise or Sorcery …
=> Add password_pepper feature

README.rdoc, doc/base.rdoc, lib/rodauth/features/base.rb, spec/rodauth_spec.rb
In response to https://github.com/janko/rodauth-rails/issues/11, this PR adds the `session_key_prefix` configuration for prefixing all session keys. This is useful when using multiple Rodauth configurations, where it's usually desired to have the session state separated between configurations.
```rb
plugin :rodauth do
end
plugin :rodauth, name: :admin do
session_key_prefix "admin_"
end
```
cc @bjeanes
=> Add session_key_prefix configuration for adding prefix to all session keys

lib/rodauth/features/change_password.rb
I believe this has likely just been overlooked. I noticed it when the label wasn't changing when tweaking locale texts!
=> Make `new_password_label` translatable

javascript/webauthn_auth.js, javascript/webauthn_setup.js
The `webauthn` feature is designed to accommodate multiple Webauthn identies being created against a single Rodauth account. However, presently, this is broken because Rodauth is not correctly preparing the `excludeCredentials` option on credential creation options.
This PR does two things:
* Unpacks and prepares the correct representation for the credential IDs to exclude.
* Extracts the repeated packing and unpacking between (what appears to be) url-safe Base64 and the array buffer than the Webauthn browser API expects. This is purely opportunistic but it seemed like a subtle place for a bug to creep into in the future. I'm happy to excise this from the PR if you don't want this change.
There is no test for this because the Rodauth tests don't exercise JS (and Webauthn requires TLS …
=> Fix setup of subsequent Webauthn identities

lib/rodauth.rb, spec/rodauth_spec.rb
When loading a tree of dependencies, we need to immediately write down when we've loaded the dependency, otherwise in this case they can be loaded multiple times. I've added a spec that would return duplicate features with current code.
It doesn't cause any actual problems, but users of `rodauth.features` and `rodauth.routes` might rely that every feature is listed exactly once. In my case, I'm using these methods to list available routes.
=> Avoid features being loaded multiple times

lib/rodauth/features/confirm_password.rb
This PR does a minor update to the routing syntax in confirm_password feature to make it consistent with other Rodauth features.
=> Improve routing syntax consistency in confirm_password feature

doc/recovery_codes.rdoc, lib/rodauth/features/recovery_codes.rb, spec/two_factor_spec.rb
This adds an `auto_remove_recovery_codes?` option to the `recovery_codes` feature. It defaults to `false`. If set to `true` it will delete all recovery codes once the last MFA method (SMS, OTP or WebAuthn) has been removed. It won't delete recovery codes if an MFA method is removed and others are still active (e.g. disable OTP with SMS still being active).
=> Add :auto_remove_recovery_codes? option to RecoveryCodes feature

lib/rodauth/features/jwt.rb, spec/jwt_spec.rb
When sessions Roda plugin is used, `#clear_session` will call `scope.clear_session`, which unlike `session.clear` will not clear the `@session` hash.
So in JWT feature we make sure to call `session.clear` in `#clear_session` in case it wasn't called in the super method. I wasn't sure whether to add an `if scope.respond_to?(:clear_session)` here, I thought it probably wasn't worth repeating the conditional.
I also added assertions for setting empty JWT token when `#clear_session` is called but Rodauth isn't the one returning the response to the client. As I mentioned on the google group, this spec was actually the main purpose of my PR 😛 But then I discovered this potential issue through reading, so I thought I'd include a fix.
=> Fix #clear_session not clearing JWT session with sessions plugin

lib/rodauth/features/remember.rb, spec/remember_spec.rb, spec/spec_helper.rb
Secure cookies are only sent to the server when a request is made with the HTTPS scheme, and therefore are more resistant to man-in-the-middle attacks, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). Given this, I thought it might be safer make the remember cookie `secure` by default when the request is made over SSL.
I believe this is mostly a backwards compatible change, except for sites that are accessible both over `http://` and `https://`, where `http://` doesn't redirect to `https://`. However, this configuration is insecure by itself, so I thought it's fine.
I've also took the liberty of DRYing up remember feature tests a bit, and moving assertions for all cookie attributes together in a dedicated test.
=> Make remember cookie secure by default with SSL

README.rdoc, lib/rodauth.rb, spec/rodauth_spec.rb
As discussed in https://github.com/jeremyevans/rodauth/pull/151, this PR adds an `:auth_class` plugin option that allows providing a custom `Rodauth::Auth` subclass. Let's say the user has the `Rodauth::Auth` subclasses defined as follows:
```rb
class RodauthMain < Rodauth::Auth
configure do
end
end
```
```rb
class RodauthAdmin < Rodauth::Auth
configure do
end
end
```
Previously it was possible to specify these classes by overriding `opts[:rodauths]`:
```rb
class RodauthApp < Roda
opts[:rodauths] = {
nil => RodauthMain,
:admin => RodauthAdmin,
}
plugin :rodauth do
end
end
```
The new `:auth_class` option makes this easier:
```rb
class RodauthApp < Roda
plugin :rodauth, auth_class: RodauthMain do
end
plugin :rodauth, name: :admin, auth_class: RodauthAdmin do
end
end
```
=> Add :auth_class plugin option for providing a specific Rodauth::Auth subclass

lib/rodauth/features/reset_password.rb, spec/reset_password_spec.rb
Set @password_field_autocomplete_value = 'new-password' for the reset-password feature
=> Use new-password autocomplete value for password field when resetting password

lib/rodauth.rb, spec/rodauth_spec.rb
When using the approach of passing `Rodauth::Auth` subclasses explicitly via the `:auth_class` option, the auth class would be configured already, so in this case it would be convenient to be able to skip passing the block when loading the plugin.
```rb
class RodauthMain < Rodauth::Auth
configure do
end
end
```
```rb
plugin :rodauth, auth_class: RodauthMain
```
I was thinking whether I should move this into `Rodauth::Auth.configure`, or still require the block when `:auth_class` is not passed in, so that it's not possible to set up a `Rodauth::Auth` subclass without the `:base` feature loaded. What are your thoughts on this?
=> Allow not passing a block when loading the plugin

lib/rodauth/features/change_login.rb, lib/rodauth/features/login_password_requirements_base.rb
Found two messages, which wasn't translatable through `translate` method
=> Translate remaining error messages in ChangeLogin and LoginPasswordRequirementsBase

doc/active_sessions.rdoc, lib/rodauth/features/active_sessions.rb
This allows overriding the active session insert hash to add additional values, which makes it easier to assign things such as IP address, device type, or country/city to active sessions, for giving the user a better overview of their active sessions.
```rb
active_session_insert_hash do
super.merge(
ip: request.ip,
user_agent: request.user_agent,
...
)
end
```
=> Allow setting additional values to the active session record

doc/error_reasons.rdoc, lib/rodauth/features/active_sessions.rb, lib/rodauth/features/base.rb, lib/rodauth/features/confirm_password.rb, lib/rodauth/features/email_auth.rb, lib/rodauth/features/lockout.rb, lib/rodauth/features/otp.rb, lib/rodauth/features/reset_password.rb, lib/rodauth/features/session_expiration.rb, lib/rodauth/features/single_session.rb, lib/rodauth/features/sms_codes.rb, lib/rodauth/features/two_factor_base.rb, lib/rodauth/features/verify_account.rb, lib/rodauth/features/verify_login_change.rb, lib/rodauth/features/webauthn.rb, spec/active_sessions_spec.rb, spec/confirm_password_spec.rb, spec/email_auth_spec.rb, spec/http_basic_auth_spec.rb, spec/jwt_refresh_spec.rb, spec/jwt_spec.rb, spec/lockout_spec.rb, spec/login_spec.rb, spec/reset_password_spec.rb, spec/session_expiration_spec.rb, spec/single_session_spec.rb, spec/two_factor_spec.rb, spec/verify_account_spec.rb, spec/verify_login_change_spec.rb, spec/webauthn_spec.rb
This is a follow up to #162
`set_error_reason` was not called on redirections It is now set everywhere `set_redirect_error_status` is called.
Documentation has been updated with the new reasons, I tried to reuse the existing ones where possible.
=> More set_error_reason support

templates/button.str, templates/change-password.str, templates/global-logout-field.str, templates/login-confirm-field.str, templates/login-display.str, templates/login-field.str, templates/otp-auth-code-field.str, templates/otp-setup.str, templates/password-confirm-field.str, templates/password-field.str, templates/recovery-auth.str, templates/remember.str, templates/sms-code-field.str, templates/sms-setup.str, templates/webauthn-remove.str
[Bootstrap 5.0 was released](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/) yesterday. This PR updates the templates with some of the changes:
* label tags now require the `form-label` class
* `form-group` class has been removed, the official docs use `mb-3` instead, so we use them here as well
=> Update templates for Boostrap 5

lib/rodauth/features/internal_request.rb
As discussed on the google group, this modifies instantiating of internal rodauth instance in a way that doesn't require the internal rodauth class to be registered on the roda class. This helps it remain invisible when introspecting the roda class.
=> Remove registration of internal rodauth class

lib/rodauth/features/base.rb, lib/rodauth/features/internal_request.rb, spec/rodauth_spec.rb
Rodauth allows configuring the domain via the `#domain` configuration method:
```rb
domain "example.com"
```
However, this domain wasn't used when generating full URLs via `#route_url`, because that uses `Rack::Request#base_url`, which reads the host from the rack env. This becomes an issue when using the internal_request feature, which sets the host in rack env to an invalid domain that is expected to be overridden. Setting the `#domain` gets rid of the error, but email links will still use the invalid placeholder domain.
This PR fixes the issue by modifying `#base_url` to use the configured domain. To retain backwards compatibility with proxies, we also change `#domain` to read from `Rack::Request#authority`, which is what `Rack::Request#base_url` reads from as well.
Let me know if you …
=> Use configured domain in email links and other URLs

doc/internal_request.rdoc, lib/rodauth/features/internal_request.rb, spec/rodauth_spec.rb
To give the user all available information about why an internal request failed, we include flash, reason, and field errors in the exception message, and also expose this data via attributes on the exception object.
=> Expose flash, reason, and field errors on InternalRequestError

lib/rodauth/features/internal_request.rb
This is a really small thing, but I noticed that `#lock_account` in internal_request feature can be implemented without setting `@account` (at least without any test failures), so I thought it's worth the change.
=> Implement `#lock_account` without setting `@account`

lib/rodauth/features/internal_request.rb, spec/json_spec.rb
When `#only_json?` is set to true, the JSON feature requires that requests have `Content-Type` and `Accept` headers set to JSON. This is not the case in internal requests, which have a form-data content type set up.
Since in internal requests we don't want to deal with HTTP-level requirements, we set `#only_json?` to false in the internal auth class to allow non-JSON requests. This should be fine, because in internal requests params are grabbed from an internal hash anyway.
=> Make internal requests work in JSON-only mode

lib/rodauth/features/verify_account.rb, spec/verify_account_spec.rb
When attempting to login to an unverified account, it causes the form for resending verification email was displayed, and currently the response status is 200 OK. This was probably unintentional, because Rodauth generally uses 4xx status codes to render error responses.
So, we change this response to use a 4xx status code as well. This improves compatibility with Turbo, which expects form submits to either redirect or return a non-2xx status code.
=> Set error status in verification request response

lib/rodauth/features/verify_account.rb, spec/lockout_spec.rb, spec/verify_account_spec.rb
In #177 I missed another place in verify_account where error status should be set, which is when an unverified account exists when attempting to create an account.
I've switched to using `#set_response_error_reason_status`, as that's used in most other places. I've also added a test for the lockout feature that asserts that a 4xx response status is set when showing the lockout page.
=> Return error status when unverified account exists on account creation

www/pages/documentation.erb
It was missing the `_rdoc` suffix.
=> Fix link to path_class_methods plugin

CONTRIBUTING, www/pages/development.erb
This PR just fixes a minor typo from 36d7c7ad6276f6a4631dced58c6750c4776a4638
=> Remove duplicate word in Reporting Bugs section of website and mention GitHub Discussions in a couple more places

lib/rodauth/features/active_sessions.rb, spec/active_sessions_spec.rb
Noticed this while adding active_sessions to a project. This seemed minor enough that we don't need to add a spec for it but I can if you think we should!
=> Fix spelling of global_logout_label default in active_sessions feature

README.rdoc, lib/rodauth/features/base.rb, spec/rodauth_spec.rb
*Follow-up to the discussion in https://github.com/jeremyevans/rodauth/discussions/210*
This allows ensuring the account exists in the database before proceeding with the request. This is useful for preventing errors in development when the account record has been manually deleted, or if the account record has been deleted in production for whatever reason, and the performance impact of fetching the account record on each request is acceptable.
=> Make `#require_account` method public

lib/rodauth/features/base.rb, spec/verify_account_spec.rb
If Rodauth is configured to use a password hash column on the accounts table, and to require password on account verification, there is an extra bcrypt hashing that occurs while updating the account hash in memory after updating it in the database.
Because the values used to update the account will contain a `BCrypt::Password` object, and `BCrypt::Password#==` will perform password hashing on the right-hand operand (even for non-string operands), the comparison with `Sequel::CURRENT_TIMESTAMP` will cause it to be hashed, using the same cost that password hashing uses. I found this out when profiling an account verification request that was taking 500ms+ locally, which seemed too long for a default password hash cost.
We fix that by using `Object#equal?`, which compares object ids …
=> Avoid extra bcrypt hashing on account verification when using password hash column

doc/guides/paths.rdoc
When changing `login_route` as prescribed in the guide, developers of non API only apps will likely want to also update `require_login_redirect`. I was looking into whether this was a rodauth-rails specific issue, but I am not familiar enough to tell, and will leave this as draft.
=> Update paths.rdoc guide to include use of `require_login_redirect`

lib/rodauth/features/sms_codes.rb, spec/two_factor_spec.rb
On SMS setup and authentication, `sms_code` is added to the list of methods the session is authenticated by. However, when removing all multifactor authentication methods, Rodauth is removing `sms_codes` method, which will cause the account authenticated via SMS to stay SMS authenticated. We fix that by removing `sms_code` method instead.
The method deletion from session when removing all MFA methods wasn't tested for any MFA method (except implicitly for recovery codes), so we add the missing tests.
=> Fix removing all MFA methods not removing SMS session

doc/otp.rdoc, doc/recovery_codes.rdoc, lib/rodauth/features/otp.rb, lib/rodauth/features/recovery_codes.rb, lib/rodauth/features/sms_codes.rb
This is symmetrical to the `#sms_available?` method from the sms_codes feature. These methods should make it easier for the developer to manually generate authentication links, for cases when they cannot use `#two_factor_auth_links`.
In my case, I wanted that requiring multifactor authentication always redirects to the OTP auth page, and that links for authenticating via SMS or recovery code are displayed below the form. This way I would eliminate an additional click needed to get to the recommended MFA page (assuming TOTP is the primary method).
```erb
<% if rodauth.recovery_codes_available? %>
<%= link_to "Authenticate Using Recovery Code", rodauth.recovery_auth_path %>
<% end %>
<% if rodauth.sms_available? %>
<%= link_to "Authenticate Using SMS Code", rodauth.sms_request_path, data: { …
```
=> Add `#otp_available?` and `#recovery_codes_available?` auth methods

doc/guides/paths.rdoc, lib/rodauth/features/base.rb, spec/rodauth_spec.rb
There are use cases where it makes sense to want to disable certain routes (see https://github.com/janko/rodauth-rails/discussions/110). It appears that setting the `*_route` method to `nil` works, while still keeping the internal request functionality intact. If you agree, I thought it would be useful to have it documented in an official guide.
=> Ensure routes can be disabled by setting `*_route` to `nil`/`false`

doc/argon2.rdoc, doc/password_pepper.rdoc, lib/rodauth/features/argon2.rb, spec/login_spec.rb
This allows using argon2's built-in password peppering, and avoid having to use the password_pepper feature.
We also add a security warning for bcrypt, where not having a maximum bytesize limit for passwords enables an attacker to crack the password pepper, due to bcrypt truncating passwords longer than 72 bytes. The attack consists of setting a 71-byte password, then attempting to log in with a password of 72 bytes, changing the last byte until the login succeeds (secret keys are usually alphanumeric strings, so there aren't that many possibilities). In that case, the last byte is the first byte of the pepper. Then rinse-and-repeat until the attacker obtains the whole pepper. I found this out from @rafalrothenberger's [recent talk](https://www.youtube.com/watch?v=ISPYQvnLW9c&t=336s&ab_cha …
=> Add configuration for setting argon2 secret

lib/rodauth/features/base.rb
As discussed in https://github.com/jeremyevans/rodauth/discussions/267, this is useful when sharing database tables between different Rodauth configurations, and wanting to store the account type alongside account records, as it allows filtering retrieved accounts in a single place.
Example usage:
```rb
plugin :rodauth, name: :admin do
enable :create_account, :login
before_create_account do
account[:type] = "admin"
end
auth_class_eval do
def account_table_ds
super.where(type: "admin")
end
end
end
```
=> Extract `account_table_ds` private method

lib/rodauth/features/base.rb, spec/rodauth_spec.rb
Some features such as webauthn and active sessions require `hmac_secret` to be set, but raise a cryptic error when it's missing:
```
TypeError: no implicit conversion of nil into String
```
Since it's not clear from this error that the issue is in `hmac_secret` not being set, we change this to raise an explicit `ArgumentError` (like the JWT feature does for `jwt_secret`).
=> Raise explicit error when `hmac_secret` is not set but is required

lib/rodauth/features/otp.rb
The `#` is already prepended to the passed fill color, so we need to pass it without a `#`, otherwise we get a `##fff` fill, which results in a completely black square.
Fixes https://github.com/janko/rodauth-rails/issues/169
=> Fix black QR code in TOTP feature

lib/rodauth/features/email_base.rb
The `email_from` and `email_to` methods make it easier to create custom emails in a background job, where the Rodauth instance needs to be re-created.
The `token_param_value` method makes it easier to generate an email token directly, to be used for a custom email link to a frontend app, for sending it in an HTTP request to a different service, or anything else.
Below is an example Rails setup where these would be useful:
```rb
class RodauthMain < Rodauth::Rails::Auth
configure do
send_verify_account_email do
RodauthMailer.verify_account(account_id, verify_account_key_value).deliver_later
end
end
end
```
```rb
class RodauthMailer < ActionMailer::Base
def verify_account(account_id, key)
@rodauth = rodauth(account_id)
@email_link = …
```
=> Make `email_from`, `email_to`, and `token_param_value` methods public

spec/rodauth_spec.rb
Starting from version 3.0.2, `Rack::Utils.build_nested_query` percent-escapes square brackets. See https://github.com/rack/rack/pull/1989.
=> Make Rodauth specs pass on Rack 3.0.2+

doc/webauthn.rdoc, lib/rodauth/features/webauthn.rb
I was live-streaming integrating WebAuthn with Rodauth, where users can additionally set custom names for authenticator, inspired by apps such as RubyGems.org.
I couldn't add the name column value to the insert hash without copying the code, and given that the webauthn credential from form submission isn't accessible in hooks, I also didn't find an easy way to find the inserted record so that I can update it. So, I thought it would be convenient to have an auth method that can be overridden to add additional columns to webauthn keys.
I considered storing the webauthn credential in an instance variable, to avoid having to pass arguments to `webauthn_key_insert_hash`, but saw that it required multiple changes and possibly wasn't desirable, so I chose the more conservative approach with less …
=> Extract `webauthn_key_insert_hash` auth method

lib/rodauth/features/argon2.rb, lib/rodauth/features/login_password_requirements_base.rb, lib/rodauth/features/password_pepper.rb
There are use cases where one might want to create a password hash outside of the request. The rodauth-model gem currently [calls](https://github.com/janko/rodauth-model/blob/9b654f50c284204eda4e92b322b0142a919e91dc/lib/rodauth/model/sequel.rb#L26) this method in the `#password=` setter. The rodauth-rails gem is also now [calling](https://github.com/janko/rodauth-rails/blob/0aeb841b2e9a5950182901c9b3ac2fc8f87bd787/lib/generators/rodauth/templates/test/fixtures/accounts.yml#L4) this method in Active Record fixtures, to more easily support both bcrypt and argon2 along with a potential password pepper.
=> Make `password_hash` method public

lib/rodauth/features/verify_account_grace_period.rb, spec/verify_account_grace_period_spec.rb
Checking whether the unverified grace period expired in `require_login` created a discrepancy with the `logged_in?` method, where `require_login` could now return a login required response while `logged_in?` still returns true. I introduced this back in https://github.com/jeremyevans/rodauth/pull/211.
This can be problematic in scenarios where the application does some logic based on `logged_in?` before calling `require_login`. Checking unverified grace period expiration would also be skipped in potential applications that check only `logged_in?` without calling `require_login`. Here is an example similar to what we had in a Rails app:
```rb
class App < Roda
plugin :rodauth do
end
route do |r|
@current_club = current_account.owned_club if rodauth.authenticated?
r.on "api" do …
```
=> Consider session not logged in if unverified grace period expired

doc/guides/password_requirements.rdoc
I saw in the [OWASP Authentication Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls) that setting a maximum password length is recommended to prevent long password Denial of Service attacks, so I thought it's useful to show an example in the guide.
I also recently implemented a custom password complexity validation, and since it required reading the source code, I thought it would be useful to have a concrete example in the docs that people can adapt.
=> Add password maximum length and requirements examples

lib/rodauth/features/reset_password.rb, spec/reset_password_spec.rb
The internal request auth subclass doesn't have real request context, and doesn't execute Roda's route block, so it might not have what is necessary to render view templates.
I encountered this when using Rodauth as a library, where the reset password request form failed to render due to missing session handler, raised when Rodauth attempted to generate the CSRF tag.
=> Skip rendering reset password request from on invalid login attempt for internal requests

spec/lockout_spec.rb, spec/reset_password_spec.rb, spec/verify_account_spec.rb
After https://github.com/jeremyevans/rodauth/pull/303, I found more places that are early rendering, which weren't being covered by existing internal request specs (`#before_login_attempt` & `#new_account` in verify_account, `#show_lockout_page` in lockout). Everything seems to be working fine, due to `#set_error_flash` being called before view rendering, but hopefully it's fine to add specs to ensure it continues working 🙂
=> Add more specs for early rendering on internal requests

doc/json.rdoc
This shows how the JSON response can be modified in general, which I believe isn't currently mentioned in the docs. It also makes error reasons functionality easier to discover; they're currently only mentioned in base feature docs, but they'll most likely be used for JSON APIs anyway, so I think it's useful to mention them there 🙂
=> Show adding error reason to the JSON response

doc/json.rdoc
=> Fix code tag syntax in JSON feature docs

README.rdoc, lib/rodauth/features/base.rb, lib/rodauth/features/verify_account_grace_period.rb, lib/rodauth/features/webauthn.rb, spec/rodauth_spec.rb
I find this method very convenient in other authentication frameworks, and have always wished for it to exist in Rodauth 🙂
In rodauth-rails, I provided an equivalent based on `#account_from_session`, but have recently run into a scenario where it doesn't work as expected. I could solve it in rodauth-rails, but I thought it would be useful to get it into Rodauth, as the logic is not Rails-specific.
The `#current_account` method retrieves the account record that's currently logged in, without regard to its status. This allows it to work when the account is unverified without grace period, which can happen when `create_account_autologin?` is set to `true`, and only verify_account feature is enabled. I wanted this setup because I'm working on a screencast where I'm rebuilding GitHub …
=> Add `#account!` method

doc/remember.rdoc, lib/rodauth/features/remember.rb, spec/remember_spec.rb
*Follow-up to https://github.com/jeremyevans/rodauth/discussions/311*
When extending remember deadline is turned on, this makes the user remembered for N days after their last activity, as opposed to since the last time they were autologged in via remember token. This behavior is probably closer to what the end user expects when asking the app to remember them.
To avoid executing an update on every request, we wait for a period of time before extending the remember deadline, 1 hour by default.
=> Extend remember deadline also while logged in

doc/active_sessions.rdoc, lib/rodauth/features/active_sessions.rb
This is useful when implementing session revoking, where we want to delete a specific session from the database that's not the current session, in order to log that browser out of the app.
This requires a HMAC'ed session ID, because it's intended to be called using a session ID retrieved from the database, which is HMAC'ed.
=> Extract `remove_active_session(session_id)` method

CHANGELOG, README.rdoc, lib/rodauth.rb, spec/rodauth_spec.rb
This should be used if alternative view libraries will be provided. For example, if using Rodauth with Phlex to render HTML.
=> Support :render=>false plugin option

lib/rodauth/features/remember.rb
This should make the `remember_login` method a bit easier to follow, because setting the remember cookie is a bit more involved, so for me it's beneficial to name that unit of work. We also do it for `forget_login` for consistency.
=> Extract setting remember cookie into a separate method

demo-site/views/layout.erb
I was trying to run this through an erb auto formatter, and it crashed on this. Looking closely, emacs also noticed the unmatched `</div>`. Possibly the indentation in the surrounding code is a little weird and could be changed.
=> Remove unmatched </div>

README.rdoc, demo-site/rodauth_demo.rb, doc/webauthn_autofill.rdoc, doc/webauthn_login.rdoc, doc/webauthn_verify_account.rdoc, javascript/webauthn_autofill.js, lib/rodauth/features/base.rb, lib/rodauth/features/json.rb, lib/rodauth/features/webauthn.rb, lib/rodauth/features/webauthn_autofill.rb, lib/rodauth/features/webauthn_login.rb, spec/webauthn_autofill_spec.rb, templates/login-field.str, templates/webauthn-autofill.str, www/pages/documentation.erb, www/pages/why.erb
This feature activates the [autofill UI](https://passkeys.dev/docs/reference/terms/#autofill-ui) for passkeys that the browser has stored on the login page, allowing the user to skip entering their email address or submitting the login form. It implements the same UX seen in https://webauthn.io/.
It builds on top of the WebAuthn Login feature, reusing its login endpoint. It ships with separate JavaScript that activates the autofill UI on the login page, and automatically submits the WebAuthn login form when the user selects their passkey. The WebAuthn login route then retrieves the user from the WebAuthn credential ID.
This requires requires the autocomplete attribute on login field to include `webauthn`. We now need to generate WebAuthn options without first identifying the account, so …
=> Add WebAuthn Autofill feature

doc/jwt.rdoc, doc/jwt_refresh.rdoc
It's already mentioned in JWT Refresh docs, but it also works just with JWT, so I thought it's good to mention it there as well. We clarify that this implements the whitelist approach to revoking JWT tokens.
=> Mention active_sessions in JWT feature docs

doc/webauthn_login.rdoc, lib/rodauth/features/webauthn_login.rb, spec/webauthn_login_spec.rb
From the [FIDO Alliance website](allow-webauthn-to-count-for-two-factors):
> **Are passkeys considered multi-factor authentication?**
>
> Passkeys are kept on a user’s devices (something the user “has”) and — if the RP requests User Verification — can only be exercised by the user with a biometric or PIN (something the user “is” or ”knows”). Thus, authentication with passkeys embodies the core principle of multi-factor security.
To allow passwordless login via a passkey to be counted for two factors, we add a new `webauthn_login_two_factors?` configuration option, which when set to true will consider the user two-factor authenticated if they're using multifactor authentication.
This is useful for skipping classic 2nd factor methods such as TOTP, recovery codes or SMS codes, but it's …
=> Allow WebAuthn login to count for two factors

doc/internal_request.rdoc, lib/rodauth/features/internal_request.rb, lib/rodauth/features/webauthn.rb, lib/rodauth/features/webauthn_login.rb, spec/webauthn_autofill_spec.rb, spec/webauthn_login_spec.rb, spec/webauthn_spec.rb
The Rails app in my current company uses custom authentication, and for a hack week I wanted to add support for passkeys. For this I wanted to try leveraging Rodauth's implementation, by using Rodauth as a library.
This PR extends the internal_request feature with support for WebAuthn actions. Initially, the `*_params` methods were returning webauthn-ruby's credential objects, but that required manually HMAC'ing the challenge. So, I used the same approach as `otp_setup_params` and returned the data as a hash. I like that this encapsulates webauthn-ruby usage within Rodauth, and the caller just deals with plain hashes.
The webauthn feature adds `webauthn_setup_params`, `webauthn_setup`, `webauthn_auth_params`, `webauthn_auth` and `webauthn_remove` methods, the webauthn_login feature adds …
=> Add internal request support for WebAuthn

doc/webauthn_autofill.rdoc
Generating WebAuthn authentication options without the account's credentials whitelisted is a WebAuthn feature that's not tied to the autofill UI, as I recently learned, it just requires discoverable credentials.
This allows the developer to provide a button for logging in via a passkey, which should have wider browser support compared to conditional mediation. I thought it's useful to mention that in the documentation.
=> Mention that webauthn_autofill allows WebAuthn login without an email

lib/rodauth/features/internal_request.rb, spec/rodauth_spec.rb
When using Roda sessions plugin, the `clear_session` method is called on the Roda object. Similarly, when using rodauth-rails, the `reset_session` method is called on the Rails controller instance. During an internal request, neither of these will actually clear the session, as there the session hash is stored in an instance variable on the Rodauth object.
We fix this by directly clearing the session hash when in an internal request. This makes `internal_request_eval` usage more reliable.
=> Make clearing session work in internal requests

doc/guides/registration_field.rdoc, doc/guides/render_confirmation.rdoc, www/pages/documentation.erb
*Follow-up on https://github.com/jeremyevans/rodauth/discussions/360*
This is a useful technique for rendering views after successful actions, while avoiding having to define routes for those pages, which would make them accessible outside of those actions.
=> Add guide for rendering confirmation view

README.rdoc
The `+` symbols are being rendered literally, so probably because of the space we need to use the `<tt>` tag.
=> Fix code tag in README

lib/rodauth/features/create_account.rb
Following on https://github.com/janko/rodauth-rails/discussions/239, if one wants to use UUID primary keys on MySQL, one possibility is using a string column and generating UUIDs in Ruby.
```rb
create_table :accounts do
String :id, primary_key: true
end
```
```rb
before_create_account do
account[:id] = SecureRandom.uuid
end
```
However, Sequel's `#insert` appears to return `0` when the primary key is something other than an autoincrementing integer on MySQL. This causes Rodauth's `#save_account` to overwrite the generated UUID with `0` on the account hash, causing problems down the line in things like account verification.
My idea was to just modify `#save_account` to set the `:id` if it wasn't already set. My only blocker is how to write tests for this. On Postgres, the primary key value …
=> Support custom primary key in accounts table on MySQL

www/pages/documentation.erb
This external guide is a documentation of Rodauth Routes for JSON requests.
=> Update `documentation.erb` to add external guide

lib/rodauth.rb, lib/rodauth/features/base.rb, spec/rodauth_spec.rb
As discussed in https://github.com/jeremyevans/rodauth/discussions/380, this is useful for generating path or URL for current route with different parameters, while still reusing configured route definitions.
```rb
rodauth.send(:"#{rodauth.route}_path", request.GET.merge("locale" => "br"))
#=> "/create-account?locale=br"
I18n.with_locale("br") { rodauth.send(:"#{rodauth.route}_path", request.GET) }
#=> "/br/auth/create-account"
```
This is the minimal functionality needed to support this use case. I was considering also adding `current_path` and `current_url` methods that would utilize this, but thought that might be an overkill for now.
=> Allow retrieving current route name

lib/rodauth/features/base.rb, spec/spec_helper.rb, spec/two_factor_spec.rb
It's possible that an account is signed in but the record gets deleted in the database, especially in development where it's common to clear testing data. When `#uses_two_factor_authentication?` is called, it ends up calling `#has_password?`, which errors if the logged in account record doesn't exist. I thought it would be nice if Rodauth gracefully handled that.
I also made two spec changes on the way: one was to use the `PASSWORD_HASH_TABLE` constant, the other was renaming the spec name to communicate that it's testing all MFA behavior.
=> Handle deleted account when checking whether MFA is setup

lib/rodauth/features/base.rb
In rodauth-rails, I set `convert_token_id_to_integer? true` in the default generated Rodauth configuration, in order to avoid DB queries at boot time when eager loading was turned on in development. This enables rake tasks such as `db:create` to still work, which boot the application without the database existing.
However, this causes tokens to silently stop working if the primary key is later switched to UUIDs. So, I would like a way to set `convert_token_id_to_integer?` to the correct value based on primary key type, but without requiring a DB connection at configure time.
```rb
convert_token_id_to_integer? { Account.columns_hash[account_id_column.to_s].type == :integer }
```
To make this work, I wanted to propose that Rodauth skips calling `convert_token_id_to_integer?` and its schema …
=> Allow skipping DB calls on configure when overriding `convert_token_id_to_integer?`

lib/rodauth/features/active_sessions.rb, spec/active_sessions_spec.rb
When `active_sessions_ds` uses `session_value` to select active sessions, it doesn't return the sessions for not-logged in users. This makes helpers like `remove_all_active_sessions` ineffective. In such situations, we can use `account_id` as a fallback to select the active session.
=> Fallback to account_id if session_value is not set for selecting active sessions

README.rdoc
- simplify the `CREATE SCHEMA` statements (no need to repeat the schema name if `AUTHORIZATION` is the same
- prettify horizontal alignment (yeah sorry about the commit message; it's _horizontal_, not _vertical!_) so that it's easier (IMO) to see what's going on
(For the record, I did confirm with the pg docs ([15](https://www.postgresql.org/docs/15/sql-createschema.html) onwards) that this way of specifying `CREATE SCHEMA` works where you do not need to separately specify the schema name if the authorization is the same value (search for `Create a schema for user joe; the schema will also be named joe:`))
=> prettify/simplify psql statements for `Using non-default schema` scenario

www/pages/documentation.erb
It's not technically a "feature", since it doesn't provide any authentication functionality. It's more like tooling, and it made sense to put it together with the Postman documentation, since it's an alternative to that. While the Postman documentation is static and doesn't adapt to route/param changes, this is dynamic based on your actual Rodauth configuration.
=> Add rodauth-openapi to the website

doc/webauthn_autofill.rdoc, lib/rodauth/features/webauthn_autofill.rb, spec/webauthn_autofill_spec.rb
This is useful when the developer wants the ability to offer WebAuthn authentication without asking for login, but considers the autofill UI too magical for the end user, and would prefer to display an explicit "login via passkey" button instead.
The autofill UI has become even more magical in recent browser/OS versions, where the user is asked to authenticate via WebAuthn as soon as the login page is loaded. Previously, Chrome would display a passkey option in a dropdown after focusing the login field, but this is no longer the case.
This ties onto our discussion in https://github.com/jeremyevans/rodauth/discussions/363.
=> Allow disabling WebAuthn autofill UI

doc/json.rdoc, lib/rodauth/features/json.rb, lib/rodauth/features/jwt.rb, spec/json_spec.rb, spec/jwt_spec.rb, spec/spec_helper.rb
Currently, CSRF protection is only disabled for JWT requests, as those use token-based instead of cookie-based authentication. However, JSON APIs that require `Content-Type: application/json` and have reasonable CORS restrictions don't appear to be vulnerable to CSRF attacks.
Since handling CSRF tokens isn't trivial to do on the client side, we can reduce friction by disabling CSRF protection by default for _all_ JSON requests (including JWT).
This is a follow-up to the discussion in https://github.com/jeremyevans/rodauth/discussions/448.
=> Disable CSRF protection for JSON requests

demo-site/views/index.erb, lib/rodauth/features/two_factor_base.rb
This is useful for when applications want to modify configuration depending on whether 2FA is pending. For example, the Rails demo app currently redirects directly to 2FA after login:
```rb
login_redirect { uses_two_factor_authentication? && !two_factor_authenticated? ? two_factor_auth_required_redirect : super() }
login_notice_flash { uses_two_factor_authentication? && !two_factor_authenticated? ? "Please authenticate with 2nd factor" : super() }
```
(It's necessary to check `!two_factor_authenticated?` here as well, because passkey login can authenticate both factors at once.) With this method available, the code can be simplified:
```rb
login_redirect { two_factor_authentication_pending? ? two_factor_auth_required_redirect : super() }
login_notice_flash { …
```
=> Add method for when 2nd factor auth is pending

doc/guides/email_requirements.rdoc, www/pages/documentation.erb
It's useful to know how to extend email requirements, for example verify whether the email exists to guard against spammers. It complements the existing guide on customizing password requirements.
=> Add guide on customizing email requirements

lib/rodauth.rb, lib/rodauth/features/base.rb, lib/rodauth/features/jwt.rb, lib/rodauth/features/sms_codes.rb, spec/change_login_spec.rb, spec/login_spec.rb, spec/rodauth_spec.rb, spec/two_factor_spec.rb
When configuring Rodauth plugin with `render: false`, it could happen that Rodauth would attempt to render a built-in view/email template:
* attempting to render a built-in email template is possible for JSON or internal requests
* external gem might incorrectly attempt to render a view template in JSON or internal requests
* in Rails apps, people would typically use Action View for rendering view/email templates, and they might miss some when disabling Tilt
Currently, Rodauth raises a rather cryptic:
```
NoMethodError: undefined method `parse_template_opts' for an instance of #<Class:0x000000011d9e3f40>
```
I initially started adding the error in rodauth-rails, but I thought it would be beneficial to have this in Rodauth itself. And for this it made sense to me to add a custom error …
=> Raise error when attempting to render, but rendering was disabled

lib/rodauth/features/jwt.rb, spec/jwt_spec.rb
In JWT 2.10.0, the `JWT::VERSION::{MAJOR,MINOR,TINY,PRE}` constants were silently made private (see https://github.com/jwt/ruby-jwt/commit/e180765b56cb06407b39a6291d7364176f58dc0a), so use `JWT.gem_version` instead.
=> Fix compatibility with JWT 2.10+

README.rdoc, doc/CHANGELOG.old
I was looking at the docs for custom features today and noted an example usage of `configuration_eval`. I wasn't totally sure how it should be used so searched the source for it and couldn't find any usages. Digging into the source code and the commit which introduced this term to the changelog and README, I think this was a typo for `configuration_module_eval`.
=> docs: `configuration_eval` -> `configuration_module_eval`

README.rdoc
Just noticed several typos in the README, so fixing these.
=> Fix typo in README
